services:
  db:
    image: mysql:latest
    restart: always
    # for POC only, this should be loaded via .env
    environment:
      MYSQL_DATABASE: my_django_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: ./scraper_poc  # Tells Docker to look inside the folder
      dockerfile: Dockerfile  # Finds the Dockerfile inside that folder
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./scraper_poc:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=my_django_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data: